print("Здравствуйте")
print("Введите вид Вашего животного...")
vid=input()
print("...его кличку...")
name=input()
print("... и возраст.")
age=input()
print("Это",vid,"по кличке",name,"возрастом",age)
